default: &default
  auth_domain: 'localhost'
  auth_key: 'pet-tracker-auth'

development:
  <<: *default

uat:
  <<: *default

production:
  <<: *default
  auth_domain: <%= ENV['AUTH_DOMAIN'] %>
  public_jwt_key: 